/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IERC721NotQuiteEnumerable,
  IERC721NotQuiteEnumerableInterface,
} from "../../../../../../@divergencetech/ethier/contracts/erc721/ERC721Enumerator.sol/IERC721NotQuiteEnumerable";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "ownerOf",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalSupply",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IERC721NotQuiteEnumerable__factory {
  static readonly abi = _abi;
  static createInterface(): IERC721NotQuiteEnumerableInterface {
    return new utils.Interface(_abi) as IERC721NotQuiteEnumerableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC721NotQuiteEnumerable {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IERC721NotQuiteEnumerable;
  }
}
