/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as soaSol from "./SOA.sol";
export type { soaSol };
import type * as soulSol from "./SOUL.sol";
export type { soulSol };
export type { Enumerator } from "./Enumerator";
export type { StakingSimple } from "./StakingSimple";
