/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export interface TestSignatureInterface extends utils.Interface {
  functions: {
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "signerAddress()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "updateSignerAddress(address)": FunctionFragment;
    "validateSignatureMultiSig(bytes[],address,uint256[],uint256[])": FunctionFragment;
    "validateSignatureSingleSig(bytes,address,uint256[],uint256[])": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "owner"
      | "renounceOwnership"
      | "signerAddress"
      | "transferOwnership"
      | "updateSignerAddress"
      | "validateSignatureMultiSig"
      | "validateSignatureSingleSig"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "signerAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateSignerAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "validateSignatureMultiSig",
    values: [BytesLike[], string, BigNumberish[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "validateSignatureSingleSig",
    values: [BytesLike, string, BigNumberish[], BigNumberish[]]
  ): string;

  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "signerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSignerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateSignatureMultiSig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateSignatureSingleSig",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface TestSignature extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TestSignatureInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    signerAddress(overrides?: CallOverrides): Promise<[string]>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateSignerAddress(
      _signerAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    validateSignatureMultiSig(
      signature: BytesLike[],
      contractAddress: string,
      tokenIds: BigNumberish[],
      rarityWeight: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    validateSignatureSingleSig(
      signature: BytesLike,
      contractAddress: string,
      tokenIds: BigNumberish[],
      rarityWeight: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  signerAddress(overrides?: CallOverrides): Promise<string>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateSignerAddress(
    _signerAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  validateSignatureMultiSig(
    signature: BytesLike[],
    contractAddress: string,
    tokenIds: BigNumberish[],
    rarityWeight: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<boolean>;

  validateSignatureSingleSig(
    signature: BytesLike,
    contractAddress: string,
    tokenIds: BigNumberish[],
    rarityWeight: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    signerAddress(overrides?: CallOverrides): Promise<string>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateSignerAddress(
      _signerAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    validateSignatureMultiSig(
      signature: BytesLike[],
      contractAddress: string,
      tokenIds: BigNumberish[],
      rarityWeight: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<boolean>;

    validateSignatureSingleSig(
      signature: BytesLike,
      contractAddress: string,
      tokenIds: BigNumberish[],
      rarityWeight: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
  };

  estimateGas: {
    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    signerAddress(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateSignerAddress(
      _signerAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    validateSignatureMultiSig(
      signature: BytesLike[],
      contractAddress: string,
      tokenIds: BigNumberish[],
      rarityWeight: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    validateSignatureSingleSig(
      signature: BytesLike,
      contractAddress: string,
      tokenIds: BigNumberish[],
      rarityWeight: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    signerAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateSignerAddress(
      _signerAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    validateSignatureMultiSig(
      signature: BytesLike[],
      contractAddress: string,
      tokenIds: BigNumberish[],
      rarityWeight: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    validateSignatureSingleSig(
      signature: BytesLike,
      contractAddress: string,
      tokenIds: BigNumberish[],
      rarityWeight: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
