/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { IWeights, IWeightsInterface } from "../../contracts/IWeights";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint16",
        name: "index",
        type: "uint16",
      },
    ],
    name: "getRank",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IWeights__factory {
  static readonly abi = _abi;
  static createInterface(): IWeightsInterface {
    return new utils.Interface(_abi) as IWeightsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IWeights {
    return new Contract(address, _abi, signerOrProvider) as IWeights;
  }
}
